import os

ROOT_DIR = os.getcwd()
MODEL_PATH = "MODEL"
PLOT_PATH = "PLOT"
ACCURACY_PATH = "ACCURACY"
CLASSIFICATION_REPORT_PATH = "CLASSIFICATION_REPORT"
VALIDATION_REPORT_PATH = "VALIDATION_REPORT"
MODEL_SUMMARY_PATH = "MODEL_SUMMARY"
MONTAGES = "MONTAGES"
EVALUATION_REPORT = "EVALUATION_REPORT"
RESOURCE_PATH = "resources"
STATIC = "STATIC"


MODEL_VERSION_IN_WORK = "5"

EPOCHS = 200
BATCH_SIZE = 128